##########################################################
##################  共有的配置,禁止修改,违者杀无赦  #################
##########################################################
###################  spring配置  ###################
spring:
  http:
      converters:
        preferred-json-mapper: fastjson
###################  thymeleaf配置  ###################
  devtools:
      restart:
        enabled: true #是否开启开发者工具（true/false）
        additional-paths: src/main/java
        exclude: static/**,templates/**
  mvc:
      static-path-pattern: /static/**
      view:
        prefix: /templates/
  cache:
    ehcache:
      config: classpath:ehcache.xml
  profiles:
    active: prod


logging:
  level.root: info
  level.com.stylefeng: debug
  path: logs/
  file: seo.log

Rsa:
  HSH:
    Key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCC/lU8JQmUA8YBK1sabPia JfRzTYDDiueH7o8YsOWQvTKitEqjLxmSeZicK0TvrhfXUy2lyQmaxB7gzthv 5H0FAu39ARTE+rai2Ya6vt4/bc19w0q9ej+sjdAQ/sU82ift1N8bfTa8p+2F imZZdXcLyo7Ib7y1AqNpBLbv+CONpQIDAQAB


###################  beetl配置  ###################
beetl:
  delimiter-statement-start: \@   #开始结束标签(yaml不允许@开头)
  delimiter-statement-end: null
  resource-tagroot: common/tags   #自定义标签文件Root目录和后缀
  resource-tagsuffix: tag
  resource-auto-check: true #是否检测文件变化,开发用true合适，但线上要改为false


